#!/bin/sh
redcolor()
{
	echo -ne "\033[31m"
}
cleanstyle()
{
	echo -ne "\033[0m"
}
greencolor()
{
	echo -ne "\033[32m"
}
echo "Begin to check zmeu trojan horse attack"

a=`find / -name "*zmeu*"`
if [ "$a" = "" ];then
	echo -n "Not found zmeu"
	greencolor
	echo "	[Not Found]"
	cleanstyle
else
	echo -n "Found zmenu trogan horse attack!"
	redcolor
	echo "	[WARN]"
	cleanstyle
	echo $a
	echo ""
fi
